config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books
  get 'books' => 'books#index', as: 'books'
  get 'books/:id/edit' => 'books#edit', as: 'book_edit'
  get 'books/:id' => 'books#show', as: 'book'
  delete 'books/:id' => 'books#destroy', as: 'book_destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
    @books = Book.new
    @books1 = Book.all
    
    
  end
  
  def create
    book = Book.new(book_params)
    book.save
    redirect_to '/'
    
  end

  def show
    @book = Book.find(params[])
  end

  def edit
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
<tr>
  <th>Title</th>
  <th>body</th>
  <th></th>
</tr>
 <% @books1.each do |book| %>
<tr>
  <td><%= book.title %></td>
  <td><%= book.body %></td>
  <td>
    <%= link_to "Show", book_path(book.id)%>
    <%= link_to "Edit", book_edit_path(book.id) %>
    <%= link_to "Destroy", book_destroy_path(book.id), method: :delete, "data-comfirm" => "本当に削除しますか？" %>
  </td>
</tr>
</table>
<% end %>

<h2>New book</h2>

<%= form_with model: @books, url:'/books', method: :post do |f| %>
<h5>Title</h5>
<%= f.text_field :title %>

<h5>Body</h5>
<%= f.text_area :body %>

<%= f.submit 'Create Book' %>

<% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<p>Title: 
<span><%= @book.title %></span>
</p>
<p>Body: 
<span><%= @book.body %></span>
</p>

<%= link_to "Edit", book_edit_path(book.id) %>
<%= link_to "Back", books_path(book.id) %>

app/views/homes/top.html.erb
<h1>ようこそBookersへ！</h1>
  <div class=top-message>
    <p>Bookersでは、さまざまな書籍に関するあなたの意見や</p>
    <br>
    <p>印象を共有し交換することができます</p>
    <br>
  </div>
<%= link_to "start", book_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>